config/routes.rb
Rails.application.routes.draw do
  resources :products
  root "products#index"

end

app/models/product.rb
class Product < ActiveRecord::Base
	validates :name, uniqueness: true, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  	def index
  		@products = Product.all
  	end

	def create
		@product = Product.new(product_params)
 
  		if @product.save
    		redirect_to products_path
  		else
    		render "new"
  		end
	end

	def new
		@product = Product.new
	end	

	def edit
  		@product = Product.find(params[:id])
	end

	def update
  		@product = Product.find(params[:id])
 
  		if @product.update(product_params)
    		redirect_to products_path
  		else
    		render "edit"
  		end
	end

	def destroy
		@product = Product.find(params[:id])
  		@product.destroy
 
 		redirect_to products_path
	end
	
	private
  	def product_params
    	params.require(:product).permit(:name, :description, :price, :published)
  	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Productos</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/products/_form_product.html.erb
<%= form_for @product do |product| %>

  <p>
    <%= product.label :product_name %><br>
    <%= product.text_field :name %>
  </p>
  <p>
    <%= product.label :product_description %><br>
    <%= product.text_area :description%>
  </p>
  <p>
    <%= product.label :product_price %><br>
    <%= product.number_field :price %>
  </p>
  <p>
    <%= product.label :product_published_? %><br>
    <%= product.check_box :published %>
  </p>
 
  <p>
    <%= product.submit %>
  </p>
<% end %>

app/views/products/edit.html.erb
<h1>Edit article</h1>
 
<%= render 'form_product' %>
 
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<h1>Products List</h1>

<%= link_to 'New product', new_product_path %><br>
<ul>
	<% @products.each do |product| %>
		<li><%= product.name %></li>
		<p>Description: <%= product.description %></p>
		<p>Price: <%= product.price %></p>
		<p>Published status: <%= product.published? %></p>
		<p><%= link_to 'Edit', edit_product_path(product) %>  <%= link_to "Delete", product_path(product), method: :delete, data: { confirm: 'Are you sure?' } %></p>
	<% end %>
</ul>

app/views/products/new.html.erb
<h1>Create a product</h1>

<%= render "form_product" %>

<p><%= link_to "Back", products_path %></p>